#!/usr/bin/env node
/* Compiles Coach Angela's grounding (worker/persona/angela.json) into src/brain-data.js.

   persona/angela.json is the reviewable source of truth:
     canonical_facts  [{fact, support_ids, confidence}]
     entries          [{id, kind, topic, summary, quote?, source_url, source_title, outlet, source_date,
                        confidence, stale_note?, status: unreviewed|approved|rejected|held}]
     avoid_topics     [{topic, why, redirect}]
     style_guide      markdown string
   Angela's review sets status; rejected, held and low-confidence entries never reach the prompt.
   Quotes are capped at 15 words so the brain paraphrases instead of reproducing sources.

   node scripts/build-brain.mjs [--check]   (--check: validate only, don't write) */

import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(root, 'persona', 'angela.json');
const OUT = join(root, 'src', 'brain-data.js');
const KINDS = new Set(['fact', 'view', 'story', 'advice', 'phrase', 'avoid']);
const MAX_QUOTE_WORDS = 15;

const persona = JSON.parse(readFileSync(SRC, 'utf8'));
const problems = [];

const facts = (persona.canonical_facts || []).filter(f => f.fact && f.confidence !== 'low');
if (!facts.length) problems.push('no canonical facts');

const seen = new Set();
const entries = [];
let dropped = 0, trimmed = 0;
for (const e of persona.entries || []) {
  if (!e.id || seen.has(e.id)) { problems.push(`duplicate or missing id: ${e.id}`); continue; }
  seen.add(e.id);
  if (e.status === 'rejected' || e.status === 'held' || e.confidence === 'low' || e.kind === 'avoid' || !KINDS.has(e.kind)) { dropped++; continue; }
  if (!/^https?:\/\//.test(e.source_url || '')) { problems.push(`${e.id}: no source url`); dropped++; continue; }
  const out = {
    id: e.id, kind: e.kind, topic: e.topic, summary: String(e.summary).trim(),
    source_title: e.source_title, outlet: e.outlet || '', source_date: e.source_date, source_url: e.source_url,
  };
  if (e.quote) {
    const w = String(e.quote).trim().split(/\s+/);
    if (w.length > MAX_QUOTE_WORDS) { trimmed++; } else out.quote = w.join(' ');
  }
  entries.push(out);
}

const avoid = (persona.avoid_topics || []).filter(a => a.topic && a.redirect);
const style = String(persona.style_guide || '').trim();
if (!style) problems.push('no style guide');

const body = { canonical_facts: facts.map(f => ({ fact: f.fact })), entries, avoid_topics: avoid, style_guide: style };
const hash = createHash('sha1').update(JSON.stringify(body)).digest('hex').slice(0, 7);
const built = new Date().toISOString().slice(0, 10);
const data = { version: `angela-${built.replace(/-/g, '')}-${hash}`, built, ...body };

console.log(`brain: ${facts.length} facts · ${entries.length} entries (${dropped} dropped, ${trimmed} quotes trimmed) · ${avoid.length} avoid topics · style ${style.split(/\s+/).length} words`);
if (problems.length) { console.error('problems:\n- ' + problems.join('\n- ')); process.exit(1); }
if (process.argv.includes('--check')) process.exit(0);

writeFileSync(OUT, `/* GENERATED by scripts/build-brain.mjs from persona/angela.json — do not edit by hand. */\nexport default ${JSON.stringify(data, null, 1)};\n`);
console.log(`wrote ${OUT.replace(root + '/', '')} (${data.version})`);
