#!/usr/bin/env node
/* Builds the v1 seed from the web prototype's starter content (js/data.js) and its pre-rendered
   clips (assets/vo/*.mp3, found through js/vo.js):
     seed/seed.sql            tenants, invite codes, drafts, starter questions, library, prompts
     seed/.build/audio.json   which clip goes under which KV key — the key renderVoice() computes
                              for its text — for seed/upload-audio.mjs
   Output is deterministic. Rows use fixed ids and INSERT OR IGNORE, so applying it again never
   duplicates anything or undoes what an athlete has approved or edited.

     node seed/build-seed.mjs
     npx wrangler d1 execute strive-db --remote --file seed/seed.sql
     node seed/upload-audio.mjs --remote */

import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { audioKeyFor } from '../src/voice.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, '../..');
const SEED_TIME = Date.UTC(2026, 8, 29, 16);   // fixed, so rebuilding doesn't churn seed.sql
const STARTER_SOURCE = 'Starter draft — edit it or redraft it';

const PROFILE = {
  name: 'Angela Ruggiero', first_name: 'Angela', coach_name: 'Coach Angela',
  headline: 'Olympic gold medalist · Hockey Hall of Fame', sport: 'Hockey',
  photo_url: 'https://billyatminyawns.github.io/strive/assets/angela1.webp',
  hero_url: 'https://billyatminyawns.github.io/strive/assets/medals.jpg',
  badges: JSON.stringify(['4× Olympian', '4 Olympic medals', 'IOC member 2010–18']),
};

// `angela` is real: everything starts as a draft awaiting her. `angela-review` is the App Review /
// demo sandbox: the same starters arrive pre-approved so the fan side has something to show.
const TENANTS = [
  { id: 'angela', code: 'ANGELA', tag: 'ang', approved: false },
  { id: 'angela-review', code: 'REVIEW', tag: 'rev', approved: true },
];

// The prototype's STORY_PROMPTS, minus what it invented: its labels ("14 fans asked this week",
// "you mentioned it once, in 2010", "gap report") and hints made claims nobody measured.
// Its free-talk prompt is served by the API as id "free".
const PROMPTS = [
  ['sp-nagano', 'The night before Nagano', 'The night before the gold medal game: where you were, whether you slept, what was running through your head.'],
  ['sp-skates', 'Your first pair of skates', 'Where they came from, how old you were, and what you remember about them.'],
  ['sp-cut', 'The hardest cut you survived', "A time you didn't make a team, lost your spot or got benched — what happened, and what you did next."],
  ['sp-harvard', 'What Harvard taught you about hockey', 'What carried over between the classroom and the rink, in either direction.'],
  ['sp-mentor', 'The mentor who changed everything', 'A coach, teammate or teacher who shaped you — what they saw in you, and what they said.'],
  ['sp-ritual', 'Your weirdest pre-game ritual', 'Something small you did before every game. Keep it light.'],
  ['sp-class', "The masterclass you'd teach", "The class you'd most want to teach: name it, then talk through the first lesson."],
];

/* ---------- prototype content ---------- */

const ctx = { window: {} };
vm.createContext(ctx);
for (const file of ['js/data.js', 'js/vo.js']) vm.runInContext(fs.readFileSync(path.join(repo, file), 'utf8'), ctx, { filename: file });
const { Data, VO } = ctx.window;
const INBOX = Data.seed().inbox;

const clips = new Map();   // audio key → { file, duration, bytes }

function secondsOf(file) {
  try {
    const m = /estimated duration: ([\d.]+) sec/.exec(execFileSync('afinfo', [file], { encoding: 'utf8' }));
    if (m) return Math.round(Number(m[1]) * 100) / 100;
  } catch { /* afinfo is macOS-only */ }
  return Math.round(fs.statSync(file).size * 8 / 128000 * 100) / 100;   // the clips are 128 kbps CBR
}

async function clip(text) {
  const src = VO.srcFor(text);
  if (!src) throw new Error('No pre-rendered clip for: ' + text.slice(0, 70));
  const file = path.join(repo, src);
  const key = await audioKeyFor(text);
  if (!clips.has(key)) clips.set(key, { file, duration: secondsOf(file), bytes: fs.statSync(file).size });
  return { audio_key: key, duration: clips.get(key).duration };
}

/* ---------- SQL ---------- */

const lit = v => v == null ? 'NULL' : typeof v === 'number' ? String(v) : `'${String(v).replace(/'/g, "''")}'`;
const values = row => `(${Object.keys(row).join(', ')}) VALUES (${Object.values(row).map(lit).join(', ')})`;
const insertOrIgnore = (table, row) => `INSERT OR IGNORE INTO ${table} ${values(row)};`;
const upsert = (table, row, conflict, cols) =>
  `INSERT INTO ${table} ${values(row)} ON CONFLICT (${conflict}) DO UPDATE SET ${cols.map(c => `${c} = excluded.${c}`).join(', ')};`;

const sql = ['-- Generated by seed/build-seed.mjs from js/data.js — do not edit by hand.'];

for (const t of TENANTS) {
  const at = (i = 0) => SEED_TIME + i;   // stable ordering within a tenant
  sql.push('', `-- ${t.id}`);

  const bio = await clip(Data.BIO);
  // profile fields follow the seed; bio, settings and everything below stay as the athlete left them
  sql.push(upsert('athletes', {
    id: t.id, ...PROFILE, bio_text: Data.BIO, bio_status: t.approved ? 'approved' : 'draft',
    bio_audio_key: bio.audio_key, bio_duration: bio.duration, paused: 0, guard_topics: 1, guard_decline: 1, created_at: at(),
  }, 'id', Object.keys(PROFILE)));
  sql.push(insertOrIgnore('invite_codes', { code: t.code, athlete_id: t.id, active: 1, created_at: at() }));

  let i = 0;
  for (const d of Data.DROPS) {
    const published = t.approved;
    sql.push(insertOrIgnore('drops', {
      id: `d_${t.tag}_${d.id}`, athlete_id: t.id, title: d.title, script: d.script, status: published ? 'published' : 'draft',
      source: STARTER_SOURCE, ...await clip(d.script),
      // the prototype lists newest first: drop-1 is "today"
      published_at: published ? at() - Data.DROPS.indexOf(d) * 60e3 : null,
      queue_pos: null, pinned: published && d.pinned ? 1 : 0, created_at: at(i++),
    }));
  }
  for (const d of Data.DRAFT_DROPS) {
    sql.push(insertOrIgnore('drops', {
      id: `d_${t.tag}_${d.id}`, athlete_id: t.id, title: d.title, script: d.script, status: 'draft',
      source: STARTER_SOURCE, ...await clip(d.script), published_at: null, queue_pos: null, pinned: 0, created_at: at(i++),
    }));
  }

  const starters = [
    ...(t.approved ? [] : Data.KB.map(k => ({ id: k.id, text: k.q, draft: k.a, keys: k.keys }))),
    ...INBOX.map(q => ({ id: q.id, text: q.text, draft: q.draft, keys: q.kbKeys || [] })),
  ];
  i = 0;
  for (const s of starters) {
    await clip(s.draft);   // approving the starter draft unedited must find its clip
    sql.push(insertOrIgnore('questions', {
      id: `q_${t.tag}_${s.id}`, athlete_id: t.id, user_id: null, kind: 'starter', text: s.text, status: 'pending',
      draft: s.draft, draft_source: 'starter', drafting: 0, kb_keys: JSON.stringify(s.keys), saved: 0, created_at: at(i++),
    }));
  }

  if (t.approved) {
    i = 0;
    for (const k of Data.KB) {
      sql.push(insertOrIgnore('kb', {
        id: `kb_${t.tag}_${k.id}`, athlete_id: t.id, question: k.q, answer: k.a, keys: JSON.stringify(k.keys),
        ...await clip(k.a), source_question_id: null, created_at: at(i++),
      }));
    }
  }

  PROMPTS.forEach(([id, title, hint], n) => sql.push(upsert('prompts',
    { id, athlete_id: t.id, title, src: 'STARTER PROMPT', hint, sort: n }, 'athlete_id, id', ['title', 'src', 'hint', 'sort'])));
}

fs.writeFileSync(path.join(here, 'seed.sql'), sql.join('\n') + '\n');

const worker = path.resolve(here, '..');
const audio = [...clips].map(([key, c]) => ({ key, file: path.relative(worker, c.file), metadata: { duration: c.duration, bytes: c.bytes } }));
fs.mkdirSync(path.join(here, '.build'), { recursive: true });
fs.writeFileSync(path.join(here, '.build', 'audio.json'), JSON.stringify(audio, null, 1));

console.log(`seed.sql: ${sql.filter(l => l.startsWith('INSERT')).length} statements for ${TENANTS.map(t => t.id).join(' + ')}`);
console.log(`.build/audio.json: ${audio.length} clips, ${(audio.reduce((n, c) => n + c.metadata.bytes, 0) / 1e6).toFixed(1)} MB`);
